name: Print Package Info
description: Prints the package info to the console
inputs:
  package_version:
    description: 'Package version'
    required: true

runs:
  using: composite
  steps:
    - name: Print new package version info
      shell: bash
      run: |
        cat >> $GITHUB_STEP_SUMMARY << EOF
        ## 📦 Packages published

        **Version:** \`${{ inputs.package_version }}\`

        | Registry | Package |
        |----------|---------|
        | Maven | \`de.stammtischhub:terminpilot-api-spec:${{ inputs.package_version }}@yaml\` |
        | npm | \`@stammtischhub/terminpilot-api-spec@${{ inputs.package_version }}\` |
        EOF