openapi: 3.1.2
info:
  title: TerminPilot API
  version: 1.2.0

servers:
  - url: http://localhost:8080
    description: Local Development

tags:
  - name: Auth
    description: Endpoints for authentication
  - name: Event
    description: Endpoints for Events

paths:
  /api/auth/register:
    $ref: './paths/auth/register.yaml'

  /api/auth/login:
    $ref: './paths/auth/login.yaml'

  /api/auth/logout:
    $ref: './paths/auth/logout.yaml'

  /api/auth/me:
    $ref: './paths/auth/me.yaml'

  /api/evet/suggestions:
    $ref: './paths/event/suggestions.yaml'
